#!/usr/local/bin/python3

import sys, warnings, argparse, paramiko
warnings.filterwarnings(action='ignore',module='.*paramiko.*')
client = paramiko.SSHClient()

# argparser
parser =  argparse.ArgumentParser()
parser.add_argument("server", help="server on which you'll send the command")
parser.add_argument("command", help="command to send")
args = parser.parse_args()

# params
host = '192.168.1.15'
user = 'pi'
passw = 'raspberry'

# functions
def usage():
    print("nope !")

def verbose():
    print("verbose")
    print(cmd)
    print(helpmenu)

def send():
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(host, username=user, password=passw)
    #client.exec_command(cmd)
    stdin, stdout, stderr = client.exec_command(cmd)
    for line in stdout.read().splitlines():
         print (line)
    client.close()

# main code
print(args.server)
print(args.command)
